In [1]:
import pandas as pd

LIMPIEZA DE DATOS

In [9]:
df_historico_partidos = pd.read_csv('./../Data/partidos_champions_data.csv')
df_historico_partidos[df_historico_partidos['season']==1969].shape

(58, 6)

In [3]:
#ELiminamos la columna Unnamed:0
df_historico_partidos.drop(['Unnamed: 0'], axis=1, inplace=True)
df_historico_partidos.rename(columns={'Home': 'HomeTeam', 'Away':'AwayTeam','season': 'Season'}, inplace=True)

In [4]:
df_historico_partidos

           HomeTeam GoalHome GoalAway          AwayTeam  Season
0       Real Madrid        4        3             Reims    1956
1             Milan        2        1       Real Madrid    1956
2         Hibernian        0        1             Reims    1956
3       Real Madrid        4        2             Milan    1956
4             Reims        2        0         Hibernian    1956
...             ...      ...      ...               ...     ...
5567        Leipzig        1        4  Shakhtar Donetsk    2023
5568         Celtic        0        3       Real Madrid    2023
5569       Salzburg        1        1             Milan    2023
5570       Dortmund        3        0        Copenhagen    2023
5571  Dinamo Zagreb        1        0           Chelsea    2023

[5572 rows x 5 columns]

In [5]:
df_historico_partidos[df_historico_partidos['GoalHome'].str.contains('^\D')]

            HomeTeam GoalHome GoalAway         AwayTeam  Season
318            Derry        -        -       Anderlecht    1966
365           Tirana        -        -        Vålerenga    1967
382        Vålerenga        -        -           Tirana    1967
427    Dinamo Tirana        -        -     Braunschweig    1968
443     Braunschweig        -        -    Dinamo Tirana    1968
485      Ferencváros        -        -           Levski    1969
486             Ruch        -        -      Dynamo Kyiv    1969
487    Crvena zvezda        -        -             Jena    1969
501           Levski        -        -      Ferencváros    1969
502      Dynamo Kyiv        -        -             Ruch    1969
503             Jena        -        -    Crvena zvezda    1969
639          Everton      (4)      (3)  Mönchengladbach    1971
701           Celtic      (4)      (5)            Inter    1972
819           Újpest      (4)      (3)   Spartak Trnava    1974
820       Åtvidaberg      (3)      (4)           Bayern    1974
850      Cork Celtic        -        -          Omonoia    1975
864          Omonoia        -        -      Cork Celtic    1975
939        Magdeburg      (1)      (2)            Malmö    1976
1060        Juventus      (3)      (0)             Ajax    1978
1061  Torpedo Moskva      (1)      (4)          Benfica    1978
1123         Dresden      (5)      (4)         Partizan    1979
1320          Tirana        -        -      Dynamo Kyiv    1983
1328     Dynamo Kyiv        -        -           Tirana    1983
1427            Roma      (2)      (4)        Liverpool    1984
1489          Dnipro      (3)      (5)         Bordeaux    1985
1490          Berlin      (5)      (4)         Aberdeen    1985
1550            FCSB      (2)      (0)        Barcelona    1986
1551       Barcelona      (5)      (4)         Göteborg    1986
1565           APOEL        -        -         Beşiktaş    1987
1573        Beşiktaş        -        -            APOEL    1987
1611        Juventus      (1)      (3)      Real Madrid    1987
1673             PSV      (6)      (5)          Benfica    1988
1687   Crvena zvezda        -        -            Milan    1989
1734   Crvena zvezda      (2)      (4)            Milan    1989
1735           Xamax      (3)      (0)          Larissa    1989
1856   Crvena zvezda      (5)      (3)        Marseille    1991
1857           Malmö      (4)      (5)          Dresden    1991
1858  Spartak Moskva      (5)      (3)           Napoli    1991
2203            Ajax      (2)      (4)         Juventus    1996
2749          Bayern      (5)      (4)         Valencia    2001
3064        Juventus      (2)      (3)            Milan    2003
3315           Milan      (2)      (3)        Liverpool    2005
3316             PSV      (4)      (2)             Lyon    2005
3567       Liverpool      (4)      (1)          Chelsea    2007
3693      Man United      (6)      (5)          Chelsea    2008
3694           Porto      (1)      (4)          Schalke    2008
3695         Sevilla      (2)      (3)       Fenerbahçe    2008
3821            Roma      (6)      (7)          Arsenal    2009
4197          Bayern      (3)      (4)          Chelsea    2012
4198     Real Madrid      (1)      (3)           Bayern    2012
4199           APOEL      (4)      (3)             Lyon    2012
4575        Atlético      (3)      (2)       Leverkusen    2015
4701     Real Madrid      (5)      (3)         Atlético    2016
4702        Atlético      (8)      (7)              PSV    2016

En este caso, tenemos los partidos que se decidieron por penaltis (el resultado viene entre paréntesis) y los partidos que no se llegaron a disputar (vienen entre guiones). Vamos a eliminar los partidos que no se llegaron a disputar.

In [6]:
df_partidos_suspendidos = df_historico_partidos[df_historico_partidos['GoalAway'].str.contains('-')]
df_partidos_suspendidos.shape

(18, 5)

In [7]:
df_historico_partidos.drop(df_partidos_suspendidos.index, inplace = True)
df_historico_partidos.shape

(5554, 5)

Como podemos observar, se han eliminado los 18 partidos que estaban suspendidos

In [8]:
df_historico_partidos[df_historico_partidos['GoalHome'].str.contains('-')]

Empty DataFrame
Columns: [HomeTeam, GoalHome, GoalAway, AwayTeam, Season]
Index: []

In [9]:
df_historico_partidos[df_historico_partidos['GoalAway'].str.contains('-')]

Empty DataFrame
Columns: [HomeTeam, GoalHome, GoalAway, AwayTeam, Season]
Index: []

In [10]:
df_historico_partidos.dtypes

HomeTeam    object
GoalHome    object
GoalAway    object
AwayTeam    object
Season       int64
dtype: object

In [11]:
df_penaltis = df_historico_partidos[df_historico_partidos['GoalHome'].str.contains('[^\d]')]
df_penaltis

            HomeTeam GoalHome GoalAway         AwayTeam  Season
639          Everton      (4)      (3)  Mönchengladbach    1971
701           Celtic      (4)      (5)            Inter    1972
819           Újpest      (4)      (3)   Spartak Trnava    1974
820       Åtvidaberg      (3)      (4)           Bayern    1974
939        Magdeburg      (1)      (2)            Malmö    1976
1060        Juventus      (3)      (0)             Ajax    1978
1061  Torpedo Moskva      (1)      (4)          Benfica    1978
1123         Dresden      (5)      (4)         Partizan    1979
1427            Roma      (2)      (4)        Liverpool    1984
1489          Dnipro      (3)      (5)         Bordeaux    1985
1490          Berlin      (5)      (4)         Aberdeen    1985
1550            FCSB      (2)      (0)        Barcelona    1986
1551       Barcelona      (5)      (4)         Göteborg    1986
1611        Juventus      (1)      (3)      Real Madrid    1987
1673             PSV      (6)      (5)          Benfica    1988
1734   Crvena zvezda      (2)      (4)            Milan    1989
1735           Xamax      (3)      (0)          Larissa    1989
1856   Crvena zvezda      (5)      (3)        Marseille    1991
1857           Malmö      (4)      (5)          Dresden    1991
1858  Spartak Moskva      (5)      (3)           Napoli    1991
2203            Ajax      (2)      (4)         Juventus    1996
2749          Bayern      (5)      (4)         Valencia    2001
3064        Juventus      (2)      (3)            Milan    2003
3315           Milan      (2)      (3)        Liverpool    2005
3316             PSV      (4)      (2)             Lyon    2005
3567       Liverpool      (4)      (1)          Chelsea    2007
3693      Man United      (6)      (5)          Chelsea    2008
3694           Porto      (1)      (4)          Schalke    2008
3695         Sevilla      (2)      (3)       Fenerbahçe    2008
3821            Roma      (6)      (7)          Arsenal    2009
4197          Bayern      (3)      (4)          Chelsea    2012
4198     Real Madrid      (1)      (3)           Bayern    2012
4199           APOEL      (4)      (3)             Lyon    2012
4575        Atlético      (3)      (2)       Leverkusen    2015
4701     Real Madrid      (5)      (3)         Atlético    2016
4702        Atlético      (8)      (7)              PSV    2016

In [12]:
df_penaltis.shape

(36, 5)

In [13]:
df_historico_partidos.drop(df_penaltis.index, inplace=True)
df_historico_partidos.shape

(5518, 5)

In [14]:
df_historico_partidos= df_historico_partidos.astype({
                                    'GoalHome':int,
                                    'GoalAway':int
                                    }
                               )

In [15]:
df_historico_partidos.dtypes

HomeTeam    object
GoalHome     int64
GoalAway     int64
AwayTeam    object
Season       int64
dtype: object

In [16]:
df_penaltis['GoalAway']=df_penaltis['GoalAway'].str.replace('[^\d]', '', regex=True)
df_penaltis['GoalHome']=df_penaltis['GoalHome'].str.replace('[^\d]', '', regex=True)

/tmp/ipykernel_6124/737590014.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_penaltis['GoalAway']=df_penaltis['GoalAway'].str.replace('[^\d]', '', regex=True)
/tmp/ipykernel_6124/737590014.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_penaltis['GoalHome']=df_penaltis['GoalHome'].str.replace('[^\d]', '', regex=True)

In [17]:
df_penaltis

            HomeTeam GoalHome GoalAway         AwayTeam  Season
639          Everton        4        3  Mönchengladbach    1971
701           Celtic        4        5            Inter    1972
819           Újpest        4        3   Spartak Trnava    1974
820       Åtvidaberg        3        4           Bayern    1974
939        Magdeburg        1        2            Malmö    1976
1060        Juventus        3        0             Ajax    1978
1061  Torpedo Moskva        1        4          Benfica    1978
1123         Dresden        5        4         Partizan    1979
1427            Roma        2        4        Liverpool    1984
1489          Dnipro        3        5         Bordeaux    1985
1490          Berlin        5        4         Aberdeen    1985
1550            FCSB        2        0        Barcelona    1986
1551       Barcelona        5        4         Göteborg    1986
1611        Juventus        1        3      Real Madrid    1987
1673             PSV        6        5          Benfica    1988
1734   Crvena zvezda        2        4            Milan    1989
1735           Xamax        3        0          Larissa    1989
1856   Crvena zvezda        5        3        Marseille    1991
1857           Malmö        4        5          Dresden    1991
1858  Spartak Moskva        5        3           Napoli    1991
2203            Ajax        2        4         Juventus    1996
2749          Bayern        5        4         Valencia    2001
3064        Juventus        2        3            Milan    2003
3315           Milan        2        3        Liverpool    2005
3316             PSV        4        2             Lyon    2005
3567       Liverpool        4        1          Chelsea    2007
3693      Man United        6        5          Chelsea    2008
3694           Porto        1        4          Schalke    2008
3695         Sevilla        2        3       Fenerbahçe    2008
3821            Roma        6        7          Arsenal    2009
4197          Bayern        3        4          Chelsea    2012
4198     Real Madrid        1        3           Bayern    2012
4199           APOEL        4        3             Lyon    2012
4575        Atlético        3        2       Leverkusen    2015
4701     Real Madrid        5        3         Atlético    2016
4702        Atlético        8        7              PSV    2016

In [18]:
df_historico_partidos['HomeTeam'] = df_historico_partidos['HomeTeam'].str.strip()
df_historico_partidos['AwayTeam'] = df_historico_partidos['AwayTeam'].str.strip()

In [19]:
x = df_historico_partidos['HomeTeam'].unique()
len(x)

338

NameError: name 'df' is not defined